//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bodegaWSREST.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bodegasEntities : DbContext
    {
        public bodegasEntities()
            : base("name=bodegasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bodega> bodega { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<detallepedido> detallepedido { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
    }
}
