//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bodegaWSREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallepedido
    {
        public int id { get; set; }
        public string idpedido { get; set; }
        public string idproducto { get; set; }
        public decimal precio { get; set; }
        public decimal cantidad { get; set; }
    }
}
