//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bodegaWSREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallepedido
    {
        public int id { get; set; }
        public string idpedido { get; set; }
        public string idproducto { get; set; }
        public decimal precio { get; set; }
        public decimal cantidad { get; set; }
    }
}
