//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bodegaWSREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int id { get; set; }
        public string idpedido { get; set; }
        public string idcliente { get; set; }
        public string idbodega { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public string estado { get; set; }
    }
}
