//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bodegaWSREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int id { get; set; }
        public string idpedido { get; set; }
        public string idcliente { get; set; }
        public string idbodega { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public string estado { get; set; }
    }
}
