//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bodegaWSREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int id { get; set; }
        public string idproducto { get; set; }
        public string nombre { get; set; }
        public string imagen { get; set; }
        public double precio { get; set; }
        public bool activo { get; set; }
        public string idcategoria { get; set; }
        public string idbodega { get; set; }
    }
}
