//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bodegaWSREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int id { get; set; }
        public string idproducto { get; set; }
        public string nombre { get; set; }
        public string imagen { get; set; }
        public double precio { get; set; }
        public bool activo { get; set; }
        public string idcategoria { get; set; }
        public string idbodega { get; set; }
    }
}
